@@ -1,28 +1,47 @@
###############################################
##################################################

# Run GitHub's Super Linter against code base #
# Run Mr Coxall's Super Linter against code base #

###############################################
##################################################

---

name: GitHub's Super Linter
name: Mr Coxall's Super Linter


on: [push, pull_request]

on: push

jobs:

 run-linters:

   name: GitHub's Super Linter
   name: Mr Coxall's Super Linter

   runs-on: ubuntu-latest


   steps:

     - name: Check out Git repository

       uses: actions/checkout@master
       uses: actions/checkout@main


     # remove section if you do not have any htm, js or ts files!

     - name: Prettify code

       uses: Mr-Coxall/prettier_action@main

       with:

         # run Prettier and change code that needs fixing, before next section

         prettier_options: --write **/*.{html,css,js,ts,jsx,tsx,json}

         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


     - name: Run GitHub Super Linter

@@ -32,9 +51,18 @@ jobs:

         VALIDATE_ALL_CODEBASE: true

         LINTER_RULES_PATH: /

         VALIDATE_CLANG_FORMAT: false

         VALIDATE_JAVASCRIPT_STANDARD: false

         VALIDATE_JSCPD: false
         VALIDATE_PYTHON_FLAKE8: false

         VALIDATE_GITLEAKS: false # for secrets detection

         VALIDATE_JSCPD: false # for copy and paste detection

         DEFAULT_BRANCH: main

         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
